# datasource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antique_market_service?autoReconnect=true&useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5120KB
      max-request-size: 5120KB

logging:
  level:
    ROOT: INFO
    web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

# server level configurations
server:
  port: 8082
  servlet:
    context-path: /antique-market-service
